"""Deterministic fictional demo: three invented Norwegian drinks brands, twelve weeks of invented headlines.

Every brand, outlet, person, headline and URL here is fictional and generated by code. The URLs use the
reserved ``.invalid`` domain so they can never point at a real site. The demo contains one engineered
spike (a fictional Fjellbrus product recall in the final week) and decoy headlines about the aurora
("nordlyset") that the Nordlys Energi exclusions must reject.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
import math
import random

import pandas as pd

from .config import Brand
from .sentiment import LexiconScorer

DEMO_SEED = 20261001
DEMO_START = date(2026, 7, 6)  # Monday
DEMO_DAYS = 84  # 12 weeks, ending Sunday 27 September 2026
DEMO_END = DEMO_START + timedelta(days=DEMO_DAYS - 1)
SPIKE_DAYS = {date(2026, 9, 22): 13, date(2026, 9, 23): 9, date(2026, 9, 24): 4}
DEMO_NOTICE = (
    "Demo data: every brand, outlet, headline and link is fictional and generated by code. "
    "No real company or publication is described."
)

DEMO_BRANDS: tuple[Brand, ...] = (
    Brand("Fjellbrus", ("Fjellbrus", "Fjellbrus AS"), (), "own"),
    Brand("Kystkraft", ("Kystkraft",), ("Kystkraft Arena",), "competitor"),
    Brand(
        "Nordlys Energi",
        ("Nordlys Energi", "Nordlys"),
        ("nordlyset", "nordlysvarsel", "nordlys over", "nordlys i natt", "sterkt nordlys"),
        "competitor",
    ),
)

SOURCES = ("Demoavisen Vest", "Demoavisen Nord", "Demo Næringsliv", "Demo Marked", "Demoforum Brus")
SOURCE_WEIGHTS = (0.26, 0.22, 0.2, 0.18, 0.14)
CITIES = ("Bergen", "Tromsø", "Trondheim", "Stavanger", "Bodø", "Ålesund", "Lillehammer", "Kristiansand")
PRODUCTS = {
    "Fjellbrus": ("Fjellbrus Bringebær", "Fjellbrus Sukkerfri", "Fjellbrus Rabarbra"),
    "Kystkraft": ("Kystkraft Original", "Kystkraft Zero"),
    "Nordlys Energi": ("Nordlys Energi Tropisk", "Nordlys Energi Frost"),
}
BASE_RATE = {"Fjellbrus": 2.9, "Kystkraft": 2.3, "Nordlys Energi": 1.5}
TREND = {"Fjellbrus": 0.0, "Kystkraft": -0.25, "Nordlys Energi": 0.9}  # change in daily rate over the 12 weeks
TONE = {"Fjellbrus": (0.32, 0.53, 0.15), "Kystkraft": (0.22, 0.5, 0.28), "Nordlys Energi": (0.36, 0.5, 0.14)}

POSITIVE = (
    ("{brand} lanserer {product} – kundene er begeistret", "Den nye smaken ble lansert i {city} og fikk god mottakelse."),
    ("{product} kåret til sommerens beste brus", "Juryen roser den friske smaken og den nye flasken."),
    ("{brand} med rekordsalg i sommer", "Selskapet melder om sterk vekst i dagligvarehandelen."),
    ("{brand} blir ny sponsor for ungdomsfotball i {city}", "Klubben er glad for avtalen, som gjelder i tre år."),
    ("Suksess for {brand} på Matmessa i {city}", "Køen var lang hele helgen, og mange ville smake {product}."),
    ("{brand} kutter plast og får skryt av miljøvernere", "Den nye flasken er laget av resirkulert materiale. Miljøvernerne roser grepet."),
    ("Prisbelønnet design for {brand}", "Den nye etiketten vant gull i en nordisk designkonkurranse."),
    ("{brand} styrker satsingen i {city} med nye arbeidsplasser", "Fabrikken skal ansette tjue nye medarbeidere."),
    ("Testpanel: {product} er en vinner", "Panelet ga toppkarakter for smak og pris."),
    ("Eg likar den nye {product}", "Lesarane er nøgde med smaken og meiner prisen er god."),
    ("{brand} får fornøyde kunder med ny pantordning", "Kundene liker at det blir enklere å pante flaskene."),
)
NEUTRAL = (
    ("{brand} åpner nytt lager i {city}", "Lageret skal stå klart i løpet av høsten."),
    ("{brand} legger fram halvårstall", "Omsetningen endte på nivå med samme periode i fjor."),
    ("Ny daglig leder i {brand}", "Styret har ansatt en tidligere innkjøpssjef fra dagligvarebransjen."),
    ("{brand} endrer etiketten på {product}", "Endringen skal gjøre ingrediensene lettere å lese."),
    ("Slik lages {product}", "Vi besøkte produksjonslinjen i {city} en vanlig tirsdag."),
    ("{brand} vurderer eksport til Sverige", "Selskapet bekrefter at det har hatt samtaler med svenske kjeder."),
    ("{brand} flytter hovedkontoret til {city}", "Flyttingen skjer etter planen i januar."),
    ("Spørsmål til {brand} om sukkerinnhold", "Forbrukerorganisasjoner ber produsentene oppgi sukker per flaske."),
    ("{brand} deltar på bransjemøte om emballasje", "Møtet samler produsenter av drikkevarer fra hele landet."),
    ("{brand} opnar ny avdeling i {city}", "Avdelinga skal ha ti tilsette frå nyttår."),
    ("Debatt i forumet: hvor kjøper du {product}?", "Tråden har fått over hundre svar fra lesere i hele landet."),
    ("{brand} og {other} kjemper om hylleplassen", "Dagligvarekjedene reforhandler avtalene med drikkeprodusentene."),
)
NEGATIVE = (
    ("Kunder klager på smaken av {product}", "Flere skriver i sosiale medier at de er skuffet."),
    ("{brand} kritiseres for høyt sukkerinnhold", "Ernæringseksperter mener selskapet markedsfører mot barn."),
    ("Prissjokk: {product} blir dyrere", "Kundene reagerer på prishoppet i butikkene."),
    ("{brand} med svakt resultat og nedgang i salget", "Selskapet taper markedsandeler for tredje kvartal på rad."),
    ("Forsinket levering av {product} til butikkene i {city}", "Hyllene står tomme etter problemer på lageret."),
    ("{brand} refses av tilsynsmyndighetene for reklame", "Tilsynet mener reklamen er villedende og uakseptabel."),
    ("Streik ved fabrikken til {brand} i {city}", "De ansatte protesterer mot kutt i bemanningen."),
    ("Leser: {product} er dårleg og for dyr", "Innlegget har fått mange svar frå misnøgde kundar."),
)
RECALL = (
    ("{brand} tilbakekaller {product} etter funn av glassbiter", "Tilsynsmyndigheten advarer kunder mot å drikke fra de berørte flaskene."),
    ("Myndighetene: Ikke drikk {product}", "Produsenten {brand} tilbakekaller flere tusen flasker etter feil i produksjonen."),
    ("Kunder raser etter tilbakekallingen hos {brand}", "Mange klager på dårlig informasjon fra selskapet."),
    ("{brand} beklager etter tilbakekalling", "Selskapet beklager og lover å refundere alle berørte kunder."),
    ("Tilbakekallingen kan koste {brand} dyrt", "Ekspertene frykter at skandalen skader merkevaren over tid."),
    ("Butikker i {city} fjerner {product} fra hyllene", "Tilbakekallingen gjelder flasker med best før-dato i mars."),
)
DECOYS = (
    ("Sterkt nordlys over {city} i natt", "Fotografer fikk spektakulære bilder av nordlyset."),
    ("Nordlysvarsel: Godt håp for helgen", "Meteorologene venter klar himmel i nord."),
    ("Turistene strømmer til for å se nordlyset", "Hotellene i {city} melder om fullt belegg."),
)


def _poisson(rng: random.Random, lam: float) -> int:
    """Knuth's algorithm; stdlib-only so the stream is identical across numpy versions."""
    limit, k, p = math.exp(-lam), 0, 1.0
    while True:
        p *= rng.random()
        if p <= limit:
            return k
        k += 1


def _weighted(rng: random.Random, items, weights):
    roll, total = rng.random() * sum(weights), 0.0
    for item, weight in zip(items, weights):
        total += weight
        if roll <= total:
            return item
    return items[-1]


def _item(rng: random.Random, day: date, index: int, brand: str, template: tuple[str, str]) -> dict:
    others = [name for name in BASE_RATE if name != brand]
    fill = {
        "brand": brand,
        "other": rng.choice(others),
        "product": rng.choice(PRODUCTS.get(brand, ("brusen",))),
        "city": rng.choice(CITIES),
    }
    title, summary = (part.format(**fill) for part in template)
    title = title[0].upper() + title[1:]
    moment = datetime(day.year, day.month, day.day, rng.randint(5, 21), rng.randint(0, 59), tzinfo=timezone.utc)
    return {
        "url": f"https://demo.listensignal.invalid/{day:%Y/%m/%d}/sak-{index:04d}",
        "title": title,
        "summary": summary,
        "source": _weighted(rng, SOURCES, SOURCE_WEIGHTS),
        "published": moment,
    }


def _unique_title(item: dict, seen: set[str]) -> None:
    """Real feeds re-publish updated stories with a time stamp; do the same so every demo headline is distinct."""
    base, minute = item["title"], item["published"].hour * 60 + item["published"].minute
    while item["title"] in seen:
        item["title"] = f"{base} (oppdatert kl. {minute // 60 % 24:02d}.{minute % 60:02d})"
        minute += 7
    seen.add(item["title"])


def make_demo_articles(seed: int = DEMO_SEED) -> pd.DataFrame:
    """About 600 fictional feed items over 12 weeks, scored with the lexicon fallback (deterministic offline)."""
    rng = random.Random(seed)
    items: list[dict] = []
    seen_titles: set[str] = set()
    index = 0
    for offset in range(DEMO_DAYS):
        day = DEMO_START + timedelta(days=offset)
        weekend = 0.6 if day.weekday() >= 5 else 1.0
        progress = offset / (DEMO_DAYS - 1)
        for brand, base in BASE_RATE.items():
            count = _poisson(rng, max(0.2, (base + TREND[brand] * progress) * weekend))
            for _ in range(count):
                tone = _weighted(rng, ("pos", "neu", "neg"), TONE[brand])
                pool = {"pos": POSITIVE, "neu": NEUTRAL, "neg": NEGATIVE}[tone]
                candidate = _item(rng, day, index, brand, rng.choice(pool))
                _unique_title(candidate, seen_titles)
                items.append(candidate)
                index += 1
        for _ in range(SPIKE_DAYS.get(day, 0)):
            candidate = _item(rng, day, index, "Fjellbrus", rng.choice(RECALL))
            _unique_title(candidate, seen_titles)
            items.append(candidate)
            index += 1
        if rng.random() < 0.3:
            candidate = _item(rng, day, index, "", rng.choice(DECOYS))
            _unique_title(candidate, seen_titles)
            items.append(candidate)
            index += 1
    frame = pd.DataFrame(items)
    frame.insert(0, "article_id", range(1, len(frame) + 1))
    frame["published"] = pd.to_datetime(frame["published"], utc=True)
    frame["collected_at"] = frame["published"]
    results = LexiconScorer().score_items(frame["title"].tolist(), frame["summary"].tolist())
    frame["sentiment"] = [result.label for result in results]
    frame["sentiment_confidence"] = None
    frame["sentiment_scorer"] = [result.scorer for result in results]
    return frame
